### ISSUE TITLE
hitting ctrl-x inside a row crashes app~

### ISSUE THREAD

**Issue by davidpendergast** [davidpendergast/timetracker#7]
it truly is a time to be alive
```
Traceback (most recent call last):
  File "timeit.py", line 1256, in <module>
  File "kivy\app.py", line 955, in run
  File "kivy\base.py", line 574, in runTouchApp
  File "kivy\base.py", line 341, in mainloop
  File "kivy\core\window\window_sdl2.py", line 757, in mainloop
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "kivy\core\window\__init__.py", line 163, in _on_window_key_down
  File "kivy\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
  File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
  File "kivy\_event.pyx", line 1231, in kivy._event.EventObservers._dispatch
  File "timeit.py", line 861, in kb_on_key_down
  File "kivy\uix\textinput.py", line 2887, in keyboard_on_key_down
  File "kivy\uix\textinput.py", line 2984, in _handle_shortcut
  File "kivy\uix\textinput.py", line 2015, in _cut
  File "kivy\core\clipboard\__init__.py", line 73, in copy
  File "kivy\core\clipboard\__init__.py", line 86, in _copy
  File "encodings\__init__.py", line 99, in search_function
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen zipimport>", line 170, in find_spec
  File "<frozen importlib._bootstrap>", line 431, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 741, in spec_from_file_location
  File "<frozen zipimport>", line 229, in get_filename
  File "<frozen zipimport>", line 752, in _get_module_code
  File "<frozen zipimport>", line 586, in _get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DPENDE~1\\AppData\\Local\\Temp\\[MachineID - edited out for privacy]\\base_library.zip'
```

**Comment by davidpendergast** [comment]
and it does not reproduce~
